version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(actions)"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "sentence-transformers"
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: "deps(python)"
