#!/usr/bin/env python3
"""Validate and report technical closure of the source-admitted LTMD-U1 W8 Artes cohort."""
from __future__ import annotations
import csv
from collections import Counter
from pathlib import Path
PROC=Path('data/catalog/ltmd_u1_w8_processing_inventory.csv');MAN=Path('data/catalog/ltmd_u1_w8_canonical_page_manifest.csv');OCR=Path('data/catalog/ltmd_u1_w8_artes_ocr_metrics.csv');OCR_SUM=Path('data/catalog/ltmd_u1_w8_artes_ocr_summary.csv');STRUCT=Path('data/catalog/ltmd_u1_w8_artes_page_structure.csv');STRUCT_SUM=Path('data/catalog/ltmd_u1_w8_artes_page_structure_summary.csv');FRAGS=Path('data/catalog/ltmd_u1_w8_artes_fragment_manifest.csv');FRAG_SUM=Path('data/catalog/ltmd_u1_w8_artes_fragment_manifest_summary.csv');FRAG_GAPS=Path('data/catalog/ltmd_u1_w8_artes_fragment_sequence_gaps.csv');UNITS=Path('data/catalog/ltmd_u1_w8_artes_exact_content_units.csv');OVERLAP=Path('data/catalog/ltmd_u1_w8_artes_exact_viewer_overlap.csv');OUT=Path('docs/LTMD_U1_W8_COMPLETION.md')
VERSION='LTMD_U1_W8_COMPLETION_0.1';TOPOLOGY_VERSION='LTMD_U1_W8_ARTES_PROCESSING_TOPOLOGY_0.1';OCR_VERSION='LTMD_U1_W8_ARTES_OCR_0.1';STRUCT_VERSION='PAGESTRUCT_LTMD_U1_W8_ARTES_0.1';FRAG_VERSION='FRAGSEG_LTMD_U1_W8_ARTES_0.1';REUSE_VERSION='LTMD_U1_W8_ARTES_EXACT_REUSE_0.1';EXPECTED_TOTAL=20;EXPECTED_CANONICAL=16;EXPECTED_WITHHELD=4;EXPECTED_PAGES=1490;EXPECTED_ELIGIBLE=1025;EXPECTED_FRAGMENTS=14060
CLASSES=['textual','mixed_text_image','visual_only','front_matter','toc_or_navigation','bibliography_or_credits','unknown']
def read(path):
 if not path.exists():raise SystemExit(f'missing finalized W8 artifact: {path}')
 with path.open(encoding='utf-8',newline='') as f:return list(csv.DictReader(f))
def req(cond,msg):
 if not cond:raise SystemExit(f'W8 completion failed: {msg}')
def main():
 proc=read(PROC);man=read(MAN);ocr=read(OCR);ocr_sum=read(OCR_SUM);struct=read(STRUCT);struct_sum=read(STRUCT_SUM);frags=read(FRAGS);frag_sum=read(FRAG_SUM);gaps=read(FRAG_GAPS);units=read(UNITS);overlap=read(OVERLAP)
 req(len(proc)==EXPECTED_TOTAL and len({r['viewer_key'] for r in proc})==EXPECTED_TOTAL,'processing inventory cardinality');req({r['topology_version'] for r in proc}=={TOPOLOGY_VERSION},'topology version drift')
 canonical={r['viewer_key'] for r in proc if r['ocr_identity_eligible']=='1' and r['is_canonical_processing_object']=='1'};withheld={r['viewer_key'] for r in proc if r['ocr_identity_eligible']=='0'}
 req(len(canonical)==EXPECTED_CANONICAL and len(withheld)==EXPECTED_WITHHELD and not canonical&withheld,'canonical/withheld topology');req(all(next(x for x in proc if x['viewer_key']==k)['processing_mode']=='direct_canonical' for k in canonical),'canonical mode');req(all(next(x for x in proc if x['viewer_key']==k)['processing_mode']=='withheld_source' for k in withheld),'withheld mode')
 req(len(man)==EXPECTED_PAGES and {r['viewer_key'] for r in man}==canonical,'canonical page coverage');req({r['manifest_version'] for r in man}=={TOPOLOGY_VERSION},'manifest version');req(all(r['asset_status']=='source_jpeg' and r['processing_mode']=='direct_canonical' and r['sha256'] and len(r['sha256'])==64 and int(r['byte_size'])>0 for r in man),'source provenance fields');req(len({r['page_id'] for r in man})==EXPECTED_PAGES,'duplicate page IDs')
 req(len(ocr)==EXPECTED_PAGES and len(ocr_sum)==EXPECTED_CANONICAL,'OCR cardinality');req({r['ocr_version'] for r in ocr}=={OCR_VERSION},'OCR version');req({r['viewer_key'] for r in ocr}==canonical,'OCR coverage');req(all(r['source_sha256_verified']=='1' and r['ocr_status']=='ok' and r['ocr_class']!='unresolved' for r in ocr),'OCR provenance/execution');req(sum(int(r['pages']) for r in ocr_sum)==EXPECTED_PAGES and sum(int(r['sha_verified']) for r in ocr_sum)==EXPECTED_PAGES and sum(int(r['unresolved']) for r in ocr_sum)==0,'OCR summary accounting')
 text=sum(r['ocr_class']=='text_detected' for r in ocr);no_text=sum(r['ocr_class']=='no_text_detected' for r in ocr);req(text+no_text==EXPECTED_PAGES,'OCR class accounting')
 req(len(struct)==EXPECTED_PAGES and {r['viewer_key'] for r in struct}==canonical,'PAGESTRUCT coverage');req({r['classifier_version'] for r in struct}=={STRUCT_VERSION},'PAGESTRUCT version');sc=Counter(r['primary_structure'] for r in struct);req(set(sc)<=set(CLASSES),'unexpected PAGESTRUCT class');all_struct=[r for r in struct_sum if r['viewer_key']=='ALL'];req(len(all_struct)==1 and int(all_struct[0]['n_pages'])==EXPECTED_PAGES,'PAGESTRUCT ALL summary');[req(int(all_struct[0][cl])==sc[cl],f'PAGESTRUCT summary {cl}') for cl in CLASSES]
 eligible=sc['textual']+sc['mixed_text_image'];req(eligible==EXPECTED_ELIGIBLE,'FRAGSEG eligible-page count');per={k:0 for k in canonical}
 for r in struct:
  if r['primary_structure'] in {'textual','mixed_text_image'}:per[r['viewer_key']]+=1
 req(all(per.values()),'canonical viewer with zero eligible pages')
 req(len(frags)==EXPECTED_FRAGMENTS and {r['viewer_key'] for r in frags}==canonical,'FRAGSEG coverage/count');req({r['segmenter_version'] for r in frags}=={FRAG_VERSION},'FRAGSEG version');ids=[r['fragment_id'] for r in frags];req(len(ids)==len(set(ids)),'duplicate fragment IDs');req(all(r.get('text_sha256') and len(r['text_sha256'])==64 for r in frags),'fragment hash')
 all_frag=[r for r in frag_sum if r['viewer_key']=='ALL'];req(len(all_frag)==1 and all_frag[0]['segmenter_version']==FRAG_VERSION,'FRAGSEG ALL summary');req(int(all_frag[0]['fragment_count'])==len(frags),'FRAGSEG fragment summary');segmented=len({r['page_id'] for r in frags});req(segmented==EXPECTED_ELIGIBLE and int(all_frag[0]['segmented_page_count'])==segmented,'FRAGSEG eligible-page coverage');candidate=Counter(r['candidate_type'] for r in frags);req(sum(candidate.values())==len(frags),'candidate accounting');gap_slots=sum(int(r.get('missing_slot_count') or 0) for r in gaps)
 req(bool(units) and {r['analysis_version'] for r in units}=={REUSE_VERSION},'exact-reuse units/version');req(len({r['text_sha256'] for r in units})==len(units),'duplicate exact units');req({r['text_sha256'] for r in units}=={r['text_sha256'] for r in frags},'exact hash coverage');req(not overlap or {r['analysis_version'] for r in overlap}=={REUSE_VERSION},'exact overlap version');repeated=sum(int(r['occurrence_count'])>1 for r in units);cross=sum(int(r['viewer_count'])>1 for r in units);crossgen=sum(int(r['catalog_generation_count'])>1 for r in units)
 lines=['# LTMD-U1 W8 — cierre técnico de la cohorte admisible Artes','',f'Versión: `{VERSION}`.','','## Alcance y fuente',f'- Identidades históricas preservadas: **{EXPECTED_TOTAL}/{EXPECTED_TOTAL}**.',f'- Canónicos procesados: **{EXPECTED_CANONICAL}**.',f'- Identidades retenidas por fuente: **{EXPECTED_WITHHELD}**.','- Imputaciones o aliases para identidades retenidas: **0**.',f'- Páginas fuente canónicas: **{EXPECTED_PAGES:,}**.','','## OCR',f'- SHA-256 verificados: **{EXPECTED_PAGES:,}/{EXPECTED_PAGES:,}**.',f'- Texto detectado: **{text:,} ({100*text/EXPECTED_PAGES:.2f}%)**.',f'- `no_text_detected`: **{no_text:,}**.','- `unresolved`: **0**.','','## PAGESTRUCT']
 for cl in CLASSES:lines.append(f'- `{cl}`: **{sc[cl]:,}**.')
 lines+=['',f'- Páginas elegibles para FRAGSEG: **{eligible:,}**.','','## FRAGSEG',f'- Páginas con ≥1 fragmento: **{segmented:,}**.',f'- Páginas elegibles sin fragmentos: **{eligible-segmented:,}**.',f'- Fragmentos técnicos: **{len(frags):,}**.',f'- IDs únicos: **{len(set(ids)):,}**.',f'- Páginas con huecos legítimos de secuencia: **{len(gaps):,}**.',f'- Slots omitidos: **{gap_slots:,}**.','','### Tipos candidatos']
 for typ in sorted(candidate):lines.append(f'- `{typ}`: **{candidate[typ]:,}**.')
 lines+=['','## Reutilización textual exacta',f'- Unidades exactas únicas: **{len(units):,}**.',f'- Unidades repetidas: **{repeated:,}**.',f'- Unidades presentes en ≥2 visores: **{cross:,}**.',f'- Unidades presentes en ≥2 generaciones: **{crossgen:,}**.',f'- Pares de visores con ≥1 unidad exacta compartida: **{len(overlap):,}**.','','## Estado científico','Este documento cierra técnicamente la cohorte W8 con fuente admisible; **no declara completo el W8 histórico**. Las cuatro identidades 2018 retenidas permanecen explícitamente fuera del procesamiento. OCR, PAGESTRUCT, FRAGSEG y reutilización exacta son capas técnicas reproducibles; no sustituyen una referencia humana ni validan categorías históricas o semánticas.']
 OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text('\n'.join(lines)+'\n',encoding='utf-8');print(OUT.read_text(encoding='utf-8'))
if __name__=='__main__':main()
